### PR TITLE
Add features argument to only include certain features

### PR DESCRIPTION
**Pull request by mnwright**
Example: 
````R
library(glex)
library(xgboost)

x <- as.matrix(mtcars[, -1])
y <- mtcars$mpg

xg <- xgboost(data = x, label = y, params = list(max_depth = 4, eta = .1), nrounds = 100, verbose = 0)

glex(xg, x, features = c("cyl", "disp"))
````

The SHAP values are not correct anymore if we use this. But we should have the same problem with `max_interaction`?

### CODE REVIEW

**Comment by jemus42** [comment]
Interesting idea, kind of a natural extension to the `max_interaction` situation I guess.
We could analogously calculate a remainder term, or add to the existing remainder term.
It becomes a bit wonky at the point where we limit `glex()` in both `max_interaction` and included features, at which point the remainder term sucks up both higher order interactions and entire features 🤔 

Off the top of my head I'm not sure if I completed the remainder term stuff for both xgboost and rpf or just rpf, but I'd like to note that handling that is unfortunately quite fiddly, especially for the multiclass case 🫠

**Comment by jemus42** [comment]
Is this also superseded by #17?

**Comment by mnwright** [comment]
Yes, just a small thing that is in #18 now.

**Comment by mnwright** [comment]
Wait, what about the tests?

**Comment by jemus42** [comment]
The tests in `"tests/testthat/test-glex-xgboost.R"` are in `master`, seems about right.

**Pull request closed without merging**
