### PR TITLE
Optimize FastPD by only computing components up to max_interaction

### PR DESCRIPTION
**Pull request by jyliuu**
This PR improves the existing FastPD implementation when max_interaction is set, by only computing the necessary PD functions for the functional decomposition

### CODE REVIEW

**Comment by jyliuu** [comment]
The empirical leaf-weighting did not compute the probabilities correctly before, which resulted in the failed tests. However, FastPD now does it correctly, so we should deprecate the empirical leaf-weighting in the future - we can consider only using it for tests.

**Review by jemus42 — COMMENTED** [review]
If I understood Marvin's previous comment about `<` vs `<=` correctly, the `<=` bit is a general random forest thing, not ranger-specific per se, yes?

So now the code explicitly distinguishes between either XGBoost or ranger, with an `is_ranger` flag and everything -- but in principle you might want to extend glex to also work with other random forest implementations (like randomForestSRC), or other gradient boosting learners, so maybe this should be more of an enum situation, choosing between the boosting case and the forest case?

I also realize that question is not very specific to this PR, but once again, can't say much about the actual code ¯\\\_(ツ)_/¯

**Comment by jyliuu** [comment]
> If I understood Marvin's previous comment about `<` vs `<=` correctly, the `<=` bit is a general random forest thing, not ranger-specific per se, yes?
> 
> So now the code explicitly distinguishes between either XGBoost or ranger, with an `is_ranger` flag and everything -- but in principle you might want to extend glex to also work with other random forest implementations (like randomForestSRC), or other gradient boosting learners, so maybe this should be more of an enum situation, choosing between the boosting case and the forest case?
> 
> I also realize that question is not very specific to this PR, but once again, can't say much about the actual code ¯\_(ツ)_/¯

Yes you are absolutely right! I have renamed `is_ranger` to `is_weak_inequality` to make it more generalizable. There can be two types of tree-estimators the `<=` type and the `<` type.

**Review by mnwright — APPROVED** [review]
Looks good! It gave a huge speedup for `max_interaction=2` from what I have tried. I haven't  checked all the C++ code, though.

**Pull request merged**
